### PR TITLE
Add Juicy/tattoo to trigger Juicy/imported-template tests after each build

### PR DESCRIPTION
**Pull request by tomalec**
https://github.com/Starcounter/RebelsLounge/issues/64

### CODE REVIEW

**Comment by tomalec** [comment]
ping @warpech  @PatrykSzwer  I'd disregard failing travis, it's a separate issue, as you can see here 
https://github.com/Juicy/juicy-html/tree/debug-travis and here https://travis-ci.org/Juicy/juicy-html/builds

**Comment by warpech** [comment]
Can you please explain (perhaps in the README.md of Juicy/tattoo) how will the build of `imported-template` know which version of `juicy-html` to choose?

In https://github.com/Juicy/tattoo/blob/455d9f5af88df3c20d9b84bb63133a801d037658/juicy-tattoo.js#L52 it looks as if it always takes `master`.

**Comment by tomalec** [comment]
Yes, that's easiest possible step, to get viable effect. As the title states, it calls `imported-template` tests after **each** build. It's using master branch only, but that's already something that would let avoid many problems we had in the past.

**Comment by warpech** [comment]
So that's not usable for verifying PRs before the merge.

Then I suggest to add this to `.travis.yml` in `juicy-html` at minimum:

```
branches:
  only:
  - master
```

I have made an issue about a possible long term solution: https://github.com/Juicy/tattoo/issues/1

**Comment by tomalec** [comment]
> So that's not usable for verifying PRs before the merge.

You're right, but it's useful after PR merge.

AFAIK
```
branches:
  only:
  - master
```
Would stop firing any builds for other branches, and we would like to run `juicy-html` tests for those.

**Pull request merged**
